/**
 * CropWise Agronomic Knowledge Base
 * Detailed agronomic data for 16+ key Indian crops with soil compatibility,
 * seasonal windows, water requirements, duration, yields, and agro-climatic zones.
 */

const CROPS_DATA = [
  {
    id: "cotton",
    name: "Cotton (कापूस / कपास)",
    enName: "Cotton",
    hiName: "कपास",
    mrName: "कापूस",
    icon: "🌱",
    soilTypes: ["Black Soil", "Alluvial Soil", "Clay Loam", "Red Soil"],
    seasons: ["Kharif"],
    preferredStates: ["Maharashtra", "Gujarat", "Telangana", "Andhra Pradesh", "Karnataka", "Madhya Pradesh", "Punjab", "Haryana", "Rajasthan"],
    waterReq: "Medium (500–700 mm)",
    waterLevel: "Medium",
    duration: "140–170 Days",
    yieldPerAcre: "10–14 Quintals",
    mandiRate: 7250, // ₹ per quintal
    costPerAcre: 24000,
    optimalPh: [6.0, 7.8],
    reasons: {
      en: "Black soil retains ideal deep root moisture. Warm Kharif temperatures and long growing periods yield premium fiber quality with strong APMC demand.",
      mr: "काळ्या कसदार जमिनीत ओलावा टिकून राहतो. खरीप हवामान आणि दीर्घ वाढीचा काळ उच्च दर्जाचे कापूस उत्पादन व बाजारभाव मिळवून देतो.",
      hi: "काली मिट्टी नमी को लंबे समय तक बनाए रखती है। खरीफ का मौसम और गर्म तापमान कपास की बेहतरीन गुणवत्ता और उपज के लिए सबसे उपयुक्त है।"
    },
    sowingAdvice: "Sow at the onset of monsoon (late June to early July). Row spacing: 90 × 60 cm.",
    irrigationAdvice: "Requires 4–5 critical irrigations during square formation and boll development. Avoid waterlogging.",
    fertilizerAdvice: "NPK 100:50:50 kg/ha. Apply all P & K at sowing, split Nitrogen into 3 equal doses at 30, 60 & 90 days.",
    pestAlert: "Monitor for Pink Bollworm & sucking pests. Install 5 pheromone traps/acre from 45 DAS."
  },
  {
    id: "soybean",
    name: "Soybean (सोयाबीन)",
    enName: "Soybean",
    hiName: "सोयाबीन",
    mrName: "सोयाबीन",
    icon: "🫘",
    soilTypes: ["Black Soil", "Clay Loam", "Alluvial Soil", "Red Soil"],
    seasons: ["Kharif"],
    preferredStates: ["Madhya Pradesh", "Maharashtra", "Rajasthan", "Karnataka", "Telangana", "Gujarat"],
    waterReq: "Medium (450–650 mm)",
    waterLevel: "Medium",
    duration: "90–105 Days",
    yieldPerAcre: "9–12 Quintals",
    mandiRate: 4850,
    costPerAcre: 15000,
    optimalPh: [6.0, 7.5],
    reasons: {
      en: "Ideal short-duration cash crop for black and clay loam soils during monsoon. Enriches soil nitrogen for subsequent Rabi crops.",
      mr: "खरीप हंगामासाठी कमी कालावधीत उत्तम नफा देणारे पीक. काळ्या जमिनीत उत्तम पोषण मिळते आणि पुढील रब्बी पिकासाठी नत्र संवर्धन होते.",
      hi: "काली और दोमट मिट्टी में 90-105 दिनों में तैयार होने वाली नकदी फसल। यह मिट्टी में नाइट्रोजन बढ़ाकर अगली फसल को लाभ देती है।"
    },
    sowingAdvice: "Sow after 75–100 mm monsoon rainfall is received. Seed treatment with Rhizobium culture is essential.",
    irrigationAdvice: "Mostly rain-fed; provide protective irrigation during flowering and pod development if dry spell exceeds 15 days.",
    fertilizerAdvice: "NPK 30:60:40 kg/ha + 20 kg Sulphur per hectare for higher oil content.",
    pestAlert: "Watch for Girdle Beetle and Spodoptera caterpillar. Spray Neem-based formulations early."
  },
  {
    id: "wheat",
    name: "Wheat (गहू / गेहूं)",
    enName: "Wheat",
    hiName: "गेहूं",
    mrName: "गहू",
    icon: "🌾",
    soilTypes: ["Alluvial Soil", "Clay Loam", "Black Soil"],
    seasons: ["Rabi"],
    preferredStates: ["Punjab", "Haryana", "Uttar Pradesh", "Madhya Pradesh", "Rajasthan", "Bihar", "Maharashtra", "Gujarat"],
    waterReq: "Medium (400–550 mm)",
    waterLevel: "Medium",
    duration: "110–135 Days",
    yieldPerAcre: "18–24 Quintals",
    mandiRate: 2450,
    costPerAcre: 16000,
    optimalPh: [6.0, 7.5],
    reasons: {
      en: "Cool, dry winter conditions combined with well-drained loamy or black soil maximize tillering and grain weight.",
      mr: "थंड आणि कोरडे हिवाळी हवामान, निचरा होणारी जमीन आणि पाणी उपलब्धता गव्हाच्या दाण्यांचे वजन वाढवण्यासाठी अत्यंत फायदेशीर आहे.",
      hi: "सर्दियों का ठंडा मौसम और दोमट मिट्टी गेहूं की पैदावार के लिए आदर्श हैं। यह कम जोखिम में सुनिश्चित उत्पादन देती है।"
    },
    sowingAdvice: "Best sowing window is 1st to 25th November. Treat seeds with Trichoderma viride.",
    irrigationAdvice: "5–6 irrigations at critical growth stages: Crown Root Initiation (21 DAS), Tillering, Late Jointing, Flowering, and Milking.",
    fertilizerAdvice: "NPK 120:60:40 kg/ha. Apply half N and full P & K at sowing, top dress remaining N in 2 equal splits.",
    pestAlert: "Check for Yellow/Brown Rust in cool moist spells. Apply propiconazole if pustules are observed."
  },
  {
    id: "rice",
    name: "Rice / Paddy (भात / धान)",
    enName: "Rice (Paddy)",
    hiName: "धान (चावल)",
    mrName: "भात / धान",
    icon: "🍚",
    soilTypes: ["Clay Loam", "Alluvial Soil", "Black Soil"],
    seasons: ["Kharif", "Zaid"],
    preferredStates: ["West Bengal", "Uttar Pradesh", "Punjab", "Andhra Pradesh", "Tamil Nadu", "Odisha", "Bihar", "Chhattisgarh", "Maharashtra"],
    waterReq: "High (1100–1400 mm)",
    waterLevel: "High",
    duration: "115–145 Days",
    yieldPerAcre: "22–30 Quintals",
    mandiRate: 2350,
    costPerAcre: 22000,
    optimalPh: [5.5, 7.0],
    reasons: {
      en: "Clayey loam soil with high water-retention capacity coupled with heavy Kharif rainfall guarantees robust tillering and high grain yield.",
      mr: "पाणी साठवून ठेवणारी चिकण किंवा गाळाची जमीन आणि मान्सूनचा भरपूर पाऊस यामुळे भात शेतीत भरघोस उत्पादन मिळते.",
      hi: "चिकनी दोमट मिट्टी जिसमें पानी ठहराव की अच्छी क्षमता हो, धान के लिए सबसे अनुकूल है। उच्च बाजार मांग के साथ बढ़िया उपज।"
    },
    sowingAdvice: "Nursery preparation in June, transplant 21–25 days old seedlings with 2–3 seedlings per hill.",
    irrigationAdvice: "Keep shallow standing water (2–5 cm) until 10 days before harvest.",
    fertilizerAdvice: "NPK 100:50:50 kg/ha + 25 kg Zinc Sulphate per hectare to prevent Khaira disease.",
    pestAlert: "Watch for Stem Borer and Brown Planthopper. Maintain proper field drainage."
  },
  {
    id: "maize",
    name: "Maize (मका / मक्का)",
    enName: "Maize",
    hiName: "मक्का",
    mrName: "मका",
    icon: "🌽",
    soilTypes: ["Alluvial Soil", "Red Soil", "Black Soil", "Clay Loam"],
    seasons: ["Kharif", "Rabi", "Zaid"],
    preferredStates: ["Karnataka", "Madhya Pradesh", "Maharashtra", "Bihar", "Rajasthan", "Andhra Pradesh", "Telangana", "Uttar Pradesh"],
    waterReq: "Medium (500–600 mm)",
    waterLevel: "Medium",
    duration: "95–115 Days",
    yieldPerAcre: "24–32 Quintals",
    mandiRate: 2220,
    costPerAcre: 18000,
    optimalPh: [6.0, 7.5],
    reasons: {
      en: "Fast-growing high-yield cereal crop that thrives across all 3 seasons in well-drained soils with high industrial and poultry feed demand.",
      mr: "निचरा होणाऱ्या सर्व प्रकारच्या जमिनीत वेगाने वाढणारे पीक. कमी पाण्यात भरपूर उत्पादन आणि पोल्ट्री व स्टार्च उद्योगातून वर्षभर मागणी.",
      hi: "अच्छे जल निकास वाली मिट्टी में बहुत तेजी से बढ़ने वाली फसल। सालभर मजबूत बाजार मांग और उच्च पैदावार।"
    },
    sowingAdvice: "Sow at 60 × 20 cm spacing. Depth 4–5 cm in moist soil.",
    irrigationAdvice: "Tasseling (flowering) and silking (cob filling) are most critical water stages.",
    fertilizerAdvice: "NPK 120:60:40 kg/ha. Apply Zinc Sulphate 20 kg/ha at basal stage.",
    pestAlert: "Monitor for Fall Armyworm (FAW) on whorl leaves. Apply Emamectin Benzoate if egg masses appear."
  },
  {
    id: "chickpea",
    name: "Chickpea / Gram (हरभरा / चना)",
    enName: "Chickpea (Gram)",
    hiName: "चना (छोला)",
    mrName: "हरभरा (चना)",
    icon: "🫛",
    soilTypes: ["Black Soil", "Alluvial Soil", "Clay Loam"],
    seasons: ["Rabi"],
    preferredStates: ["Madhya Pradesh", "Maharashtra", "Rajasthan", "Gujarat", "Uttar Pradesh", "Karnataka", "Andhra Pradesh"],
    waterReq: "Low (250–350 mm)",
    waterLevel: "Low",
    duration: "95–115 Days",
    yieldPerAcre: "7–10 Quintals",
    mandiRate: 5750,
    costPerAcre: 11000,
    optimalPh: [6.0, 8.0],
    reasons: {
      en: "Thrives in residual moisture of black soils in mild winter with minimal irrigation. Excellent price realization in APMC mandis.",
      mr: "कमी पाण्यात, काळ्या जमिनीतील शिल्लक ओलाव्यावर रब्बी हंगामात येणारे अतिशय फायदेशीर कडधान्य पीक.",
      hi: "कम पानी में तैयार होने वाली रबी की सबसे भरोसेमंद दलहनी फसल। बढ़िया मंडी भाव और मिट्टी को उपजाऊ बनाने में मददगार।"
    },
    sowingAdvice: "Sow between October 15 and November 15. Treat seeds with Trichoderma + Rhizobium.",
    irrigationAdvice: "1–2 irrigations only. Pre-flowering and early pod development stage. Avoid excess watering.",
    fertilizerAdvice: "NPK 20:50:20 kg/ha + 20 kg Sulphur at sowing. Foliar spray of 2% Urea at flowering.",
    pestAlert: "Helicoverpa pod borer is major pest. Use 'T' shaped bird perches and NPV sprays."
  },
  {
    id: "groundnut",
    name: "Groundnut (भुईमूग / मूंगफली)",
    enName: "Groundnut",
    hiName: "मूंगफली",
    mrName: "भुईमूग",
    icon: "🥜",
    soilTypes: ["Red Soil", "Sandy Soil", "Alluvial Soil", "Clay Loam"],
    seasons: ["Kharif", "Zaid"],
    preferredStates: ["Gujarat", "Rajasthan", "Tamil Nadu", "Andhra Pradesh", "Karnataka", "Maharashtra", "Madhya Pradesh"],
    waterReq: "Medium (450–600 mm)",
    waterLevel: "Medium",
    duration: "105–125 Days",
    yieldPerAcre: "12–16 Quintals",
    mandiRate: 6400,
    costPerAcre: 19000,
    optimalPh: [6.0, 7.2],
    reasons: {
      en: "Friable sandy loam and red soils allow easy pegging and large pod development with high oil concentration.",
      mr: "भुसभुशीत वाळू मिश्रित लाल किंवा गाळाच्या जमिनीत आऱ्या सहज जमिनीत जाऊन शेंगांची उत्तम भर होते. भरपूर बाजारभाव मिळतो.",
      hi: "हल्की रेतीली व लाल दोमट मिट्टी मूंगफली की फलियों के विकास के लिए सर्वोत्तम है। तेल व बीज दोनों का शानदार भाव मिलता है।"
    },
    sowingAdvice: "Sow at 30 × 10 cm spacing. Apply Gypsum at 200 kg/acre at pegging stage for kernel filling.",
    irrigationAdvice: "Irrigate at flowering, pegging, and pod formation stages. Stop 7 days prior to harvest.",
    fertilizerAdvice: "NPK 20:40:40 kg/ha + 15 kg Zinc Sulphate.",
    pestAlert: "Protect against Tikka leaf spot with Mancozeb spray."
  },
  {
    id: "mustard",
    name: "Mustard (मोहरी / सरसों)",
    enName: "Mustard",
    hiName: "सरसों (राई)",
    mrName: "मोहरी / राई",
    icon: "🌻",
    soilTypes: ["Alluvial Soil", "Sandy Soil", "Clay Loam"],
    seasons: ["Rabi"],
    preferredStates: ["Rajasthan", "Haryana", "Madhya Pradesh", "Uttar Pradesh", "West Bengal", "Gujarat", "Punjab"],
    waterReq: "Low (200–350 mm)",
    waterLevel: "Low",
    duration: "100–120 Days",
    yieldPerAcre: "8–11 Quintals",
    mandiRate: 5500,
    costPerAcre: 10000,
    optimalPh: [6.0, 7.5],
    reasons: {
      en: "Requires minimal water, cold winter temperatures, and dry atmosphere for high oil synthesis and minimal input cost.",
      mr: "अतिशय कमी पाण्यात आणि कमी खर्चात रब्बीत येणारे तेलबिया पीक. थंडीच्या दिवसात हमखास नफा देते.",
      hi: "बहुत कम लागत व कम पानी में बंपर पैदावार देने वाली रबी तिलहन फसल। ठंड का मौसम तेल की मात्रा बढ़ाता है।"
    },
    sowingAdvice: "Best sowing time: October 1st to 20th. Line sowing at 30 × 10 cm.",
    irrigationAdvice: "Only 2 irrigations: 1st at flowering (30–35 DAS) and 2nd at pod filling (60–65 DAS).",
    fertilizerAdvice: "NPK 60:30:30 kg/ha + 25 kg Sulphur per hectare is mandatory for high oil percentage.",
    pestAlert: "Aphids (Mahun) attack during cloudy weather. Spray Dimethoate or neem oil."
  },
  {
    id: "sugarcane",
    name: "Sugarcane (ऊस / गन्ना)",
    enName: "Sugarcane",
    hiName: "गन्ना",
    mrName: "ऊस",
    icon: "🎋",
    soilTypes: ["Black Soil", "Alluvial Soil", "Clay Loam"],
    seasons: ["Kharif", "Rabi"],
    preferredStates: ["Uttar Pradesh", "Maharashtra", "Karnataka", "Tamil Nadu", "Gujarat", "Bihar", "Haryana", "Andhra Pradesh"],
    waterReq: "High (1500–2200 mm)",
    waterLevel: "High",
    duration: "300–365 Days",
    yieldPerAcre: "40–60 Tonnes",
    mandiRate: 340, // ₹ per quintal (FRP rate ~₹3400/tonne)
    costPerAcre: 45000,
    optimalPh: [6.5, 7.8],
    reasons: {
      en: "Deep black and alluvial soils with perennial canal or drip irrigation give assured high tonnage with government FRP payment guarantees.",
      mr: "मुबलक पाणी आणि कसदार काळी जमीन उपलब्ध असल्यास ऊस हे सर्वात सुरक्षित व खात्रीशीर वार्षिक उत्पन्न देणारे नगदी पीक आहे.",
      hi: "सिंचित क्षेत्रों और उपजाऊ मिट्टी के लिए सुनिश्चित आय वाली प्रमुख वाणिज्यिक फसल। सरकार द्वारा घोषित उचित मूल्य (FRP) की सुरक्षा।"
    },
    sowingAdvice: "Plant 2-eye bud sets treated with Carbendazim. Maintain 4 to 5 feet row spacing for drip irrigation.",
    irrigationAdvice: "Requires frequent irrigation every 8–10 days in summer and 12–15 days in winter. Drip irrigation saves 40% water.",
    fertilizerAdvice: "NPK 250:115:115 kg/ha applied in 4 splits coinciding with earthing up.",
    pestAlert: "Watch for Early Shoot Borer & White Grub. Apply Chlorpyrifos with first irrigation if needed."
  },
  {
    id: "bajra",
    name: "Pearl Millet / Bajra (बाजरी / बाजरा)",
    enName: "Pearl Millet (Bajra)",
    hiName: "बाजरा",
    mrName: "बाजरी",
    icon: "🌾",
    soilTypes: ["Sandy Soil", "Red Soil", "Alluvial Soil", "Laterite Soil"],
    seasons: ["Kharif", "Zaid"],
    preferredStates: ["Rajasthan", "Uttar Pradesh", "Gujarat", "Haryana", "Maharashtra", "Madhya Pradesh", "Karnataka"],
    waterReq: "Low (250–350 mm)",
    waterLevel: "Low",
    duration: "75–85 Days",
    yieldPerAcre: "12–16 Quintals",
    mandiRate: 2350,
    costPerAcre: 9000,
    optimalPh: [6.5, 8.2],
    reasons: {
      en: "Ultra drought-hardy millet that thrives in light sandy soils with erratic rainfall, producing nutritious grain and cattle fodder in just 80 days.",
      mr: "हलक्या आणि वाळू मिश्रित जमिनीत अगदी कमी पाण्यात अवघ्या ८० दिवसांत तयार होणारे अतिशय टिकाऊ व पोषक धान्य पीक.",
      hi: "कम बारिश और रेतीली जमीन में बिना किसी विशेष देखभाल के 75-80 दिनों में तैयार होने वाला पौष्टिक मोटा अनाज।"
    },
    sowingAdvice: "Sow with early monsoon showers. Seed rate 1.5–2 kg/acre at 45 × 12 cm spacing.",
    irrigationAdvice: "Highly drought tolerant. 1 protective irrigation during panicle emergence if rainfall fails.",
    fertilizerAdvice: "NPK 60:30:20 kg/ha. Half N at sowing, half at 30 days after sowing.",
    pestAlert: "Downy mildew resistant hybrid seeds should be selected."
  },
  {
    id: "pigeonpea",
    name: "Pigeon Pea / Tur (तूर / अरहर)",
    enName: "Pigeon Pea (Tur / Arhar)",
    hiName: "अरहर (तूर)",
    mrName: "तूर (अरहर)",
    icon: "🍲",
    soilTypes: ["Black Soil", "Red Soil", "Alluvial Soil", "Clay Loam"],
    seasons: ["Kharif"],
    preferredStates: ["Maharashtra", "Madhya Pradesh", "Karnataka", "Uttar Pradesh", "Gujarat", "Telangana", "Andhra Pradesh"],
    waterReq: "Low to Medium (400–550 mm)",
    waterLevel: "Low",
    duration: "150–180 Days",
    yieldPerAcre: "7–10 Quintals",
    mandiRate: 8100,
    costPerAcre: 14000,
    optimalPh: [6.5, 7.5],
    reasons: {
      en: "Deep tap-root system withstands dry spells in black soils. High market rate (₹7,500–8,500/qtl) yields exceptional net profit.",
      mr: "खोल मुळांमुळे दुष्काळातही तग धरते. तुरीला मिळणारा उच्च हमीभाव आणि बाजारभाव यामुळे एकरी भरघोस नफा मिळतो.",
      hi: "गहरी जड़ों के कारण सूखे को सहन करने वाली दलहनी फसल। मंडियों में सबसे ऊंचे दाम (₹8000+) और कम लागत।"
    },
    sowingAdvice: "Sow in June-July. Ideal for intercropping with Soybean or Cotton (1:4 ratio).",
    irrigationAdvice: "Requires 2–3 irrigations at critical branching, flowering, and pod-setting stages.",
    fertilizerAdvice: "NPK 25:50:25 kg/ha + 20 kg Sulphur at planting.",
    pestAlert: "Spray for Pod Borer at 50% flowering stage with Indoxacarb."
  },
  {
    id: "greengram",
    name: "Green Gram / Moong (मूग / मूँग)",
    enName: "Green Gram (Moong)",
    hiName: "मूँग",
    mrName: "मूग",
    icon: "🌱",
    soilTypes: ["Alluvial Soil", "Black Soil", "Red Soil", "Clay Loam"],
    seasons: ["Zaid", "Kharif"],
    preferredStates: ["Rajasthan", "Maharashtra", "Madhya Pradesh", "Gujarat", "Andhra Pradesh", "Tamil Nadu", "Punjab", "Haryana"],
    waterReq: "Low (200–300 mm)",
    waterLevel: "Low",
    duration: "60–70 Days",
    yieldPerAcre: "5–7 Quintals",
    mandiRate: 7800,
    costPerAcre: 8500,
    optimalPh: [6.2, 7.5],
    reasons: {
      en: "Quick 65-day short summer/monsoon catch crop that fits neatly between Rabi harvest and Kharif sowing with high profit per day.",
      mr: "अवघ्या ६० ते ६५ दिवसांत तयार होणारे जलद कडधान्य पीक. उन्हाळी हंगामात कमी पाण्यात उत्तम नफा आणि जमिनीची सुपीकता वाढते.",
      hi: "मात्र 60-65 दिनों में तैयार होने वाली दलहनी फसल। रबी के बाद खाली खेत में जायद मूंग उगाकर अतिरिक्त मुनाफा कमाएं।"
    },
    sowingAdvice: "Sow in March for summer crop or late June for Kharif. Seed rate 8 kg/acre.",
    irrigationAdvice: "Requires 3–4 light irrigations at 10–12 day intervals in summer. Stop when pods start turning black.",
    fertilizerAdvice: "NPK 20:40:20 kg/ha with Rhizobium seed inoculation.",
    pestAlert: "Protect from Yellow Mosaic Virus (YMV) transmitted by whitefly."
  },
  {
    id: "potato",
    name: "Potato (बटाटा / आलू)",
    enName: "Potato",
    hiName: "आलू",
    mrName: "बटाटा",
    icon: "🥔",
    soilTypes: ["Alluvial Soil", "Clay Loam", "Sandy Soil"],
    seasons: ["Rabi"],
    preferredStates: ["Uttar Pradesh", "West Bengal", "Bihar", "Gujarat", "Madhya Pradesh", "Punjab", "Maharashtra"],
    waterReq: "Medium (400–500 mm)",
    waterLevel: "Medium",
    duration: "85–110 Days",
    yieldPerAcre: "80–120 Quintals",
    mandiRate: 1450,
    costPerAcre: 35000,
    optimalPh: [5.2, 6.5],
    reasons: {
      en: "Loose alluvial and sandy loam soils ensure unhindered tuber expansion with very high commercial yield and rapid market turnover.",
      mr: "भुसभुशीत गाळाच्या किंवा वाळूमिश्रित जमिनीत बटाट्याचे गड्डे मोठे पोसतात. हिवाळी हवामानात प्रचंड उत्पादन मिळते.",
      hi: "भुरभुरी दोमट मिट्टी में आलू के कंद बहुत तेजी से बढ़ते हैं। 90 दिनों में बंपर उत्पादन देने वाली प्रमुख सब्जी फसल।"
    },
    sowingAdvice: "Plant healthy sprouted seed tubers of 35–45g size at 60 × 20 cm in mid-October.",
    irrigationAdvice: "Frequent light irrigations every 7–10 days. Avoid water reaching top of ridges.",
    fertilizerAdvice: "NPK 150:80:100 kg/ha. Apply well-decomposed FYM 10 tonnes/acre before planting.",
    pestAlert: "Watch for Late Blight in cool fog. Preventive spray of Mancozeb."
  },
  {
    id: "tomato",
    name: "Tomato (टोमॅटो / टमाटर)",
    enName: "Tomato",
    hiName: "टमाटर",
    mrName: "टोमॅटो",
    icon: "🍅",
    soilTypes: ["Red Soil", "Alluvial Soil", "Clay Loam", "Black Soil"],
    seasons: ["Kharif", "Rabi", "Zaid"],
    preferredStates: ["Andhra Pradesh", "Madhya Pradesh", "Karnataka", "Gujarat", "Odisha", "West Bengal", "Maharashtra", "Tamil Nadu"],
    waterReq: "Medium (450–600 mm)",
    waterLevel: "Medium",
    duration: "110–135 Days",
    yieldPerAcre: "120–180 Quintals",
    mandiRate: 1800,
    costPerAcre: 38000,
    optimalPh: [6.0, 7.0],
    reasons: {
      en: "Versatile, high-return horticulture crop suited for well-drained soils with drip irrigation, yielding continuous multiple pickings.",
      mr: "ठिबक सिंचन आणि चांगल्या निचऱ्याच्या जमिनीत सतत तोडण्या देणारे व योग्य वेळी प्रचंड नफा मिळवून देणारे भाजीपाला पीक.",
      hi: "ड्रिप सिंचाई और अच्छी दोमट मिट्टी में लगातार तुड़ाई देने वाली उच्च मुनाफे की बागवानी फसल।"
    },
    sowingAdvice: "Transplant 25-day seedlings on raised beds with silver-black mulch paper.",
    irrigationAdvice: "Drip irrigation daily or alternate days. Staking with bamboo sticks improves fruit quality by 35%.",
    fertilizerAdvice: "NPK 120:60:60 kg/ha through fertigation in divided doses.",
    pestAlert: "Protect against Leaf Curl Virus (whitefly) and Fruit Borer."
  },
  {
    id: "onion",
    name: "Onion (कांदा / प्याज)",
    enName: "Onion",
    hiName: "प्याज",
    mrName: "कांदा",
    icon: "🧅",
    soilTypes: ["Alluvial Soil", "Clay Loam", "Black Soil", "Red Soil"],
    seasons: ["Kharif", "Rabi", "Zaid"],
    preferredStates: ["Maharashtra", "Madhya Pradesh", "Karnataka", "Gujarat", "Rajasthan", "Bihar", "Andhra Pradesh"],
    waterReq: "Medium (400–550 mm)",
    waterLevel: "Medium",
    duration: "100–125 Days",
    yieldPerAcre: "90–140 Quintals",
    mandiRate: 1950,
    costPerAcre: 32000,
    optimalPh: [6.0, 7.5],
    reasons: {
      en: "Thrives in loose, organic-rich loam or light black soil with high market demand across all Indian wholesale mandis.",
      mr: "उत्तम निचऱ्याची गाळ किंवा काळी जमीन कांदा पोसण्यासाठी अत्यंत योग्य असते. बाजारपेठेत वर्षभर प्रचंड मागणी.",
      hi: "हल्की दोमट व काली मिट्टी प्याज की गांठों के विकास के लिए उत्तम है। देशभर की मंडियों में भारी मांग।"
    },
    sowingAdvice: "Transplant 6-8 week old nursery seedlings at 15 × 10 cm spacing.",
    irrigationAdvice: "Requires 10–12 light irrigations. Stop irrigation 15 days before harvesting for better bulb storage.",
    fertilizerAdvice: "NPK 100:50:50 kg/ha + 30 kg Sulphur for pungent taste and firm skin.",
    pestAlert: "Spray for Thrips (silver streaks on leaves) with Fipronil or Profenofos."
  },
  {
    id: "sunflower",
    name: "Sunflower (सूर्यफूल / सूरजमुखी)",
    enName: "Sunflower",
    hiName: "सूरजमुखी",
    mrName: "सूर्यफूल",
    icon: "🌻",
    soilTypes: ["Black Soil", "Alluvial Soil", "Red Soil", "Clay Loam"],
    seasons: ["Kharif", "Rabi", "Zaid"],
    preferredStates: ["Karnataka", "Maharashtra", "Andhra Pradesh", "Telangana", "Bihar", "Odisha", "Haryana", "Punjab"],
    waterReq: "Low to Medium (350–500 mm)",
    waterLevel: "Low",
    duration: "85–95 Days",
    yieldPerAcre: "7–10 Quintals",
    mandiRate: 6100,
    costPerAcre: 12500,
    optimalPh: [6.5, 8.0],
    reasons: {
      en: "Highly adaptable, photo-insensitive oilseed crop that can be grown in any season with deep roots capable of extracting soil moisture.",
      mr: "कोणत्याही हंगामात येणारे आणि दुष्काळातही तग धरणारे तेलबिया पीक. कमी पाण्यात ९० दिवसांत हमखास उत्पन्न.",
      hi: "सभी मौसमों में उगाई जा सकने वाली तिलहन फसल। कम पानी और सामान्य मिट्टी में 90 दिनों में तैयार।"
    },
    sowingAdvice: "Sow at 60 × 30 cm spacing. Hand pollination during flowering increases seed set by 20%.",
    irrigationAdvice: "Irrigate at button stage, flowering, and seed development.",
    fertilizerAdvice: "NPK 60:60:30 kg/ha with 20 kg Sulphur and Boron spray at ray floret opening.",
    pestAlert: "Protect against Parakeets during seed maturity and Head Borer."
  }
];

// Supported Indian states and top agricultural districts
const LOCATIONS_DATA = [
  { state: "Maharashtra", districts: ["Nagpur", "Amravati", "Nashik", "Pune", "Aurangabad", "Solapur", "Kolhapur", "Yavatmal", "Akola", "Jalgaon", "Latur", "Nanded"] },
  { state: "Madhya Pradesh", districts: ["Indore", "Ujjain", "Bhopal", "Hoshangabad", "Dewas", "Sehore", "Gwalior", "Jabalpur", "Chhindwara", "Khargone"] },
  { state: "Punjab", districts: ["Ludhiana", "Amritsar", "Bathinda", "Patiala", "Jalandhar", "Sangrur", "Firozpur", "Gurdaspur"] },
  { state: "Haryana", districts: ["Karnal", "Hisar", "Sirsa", "Ambala", "Rohtak", "Kurukshetra", "Sonipat", "Bhiwani"] },
  { state: "Uttar Pradesh", districts: ["Varanasi", "Lucknow", "Agra", "Meerut", "Prayagraj", "Gorakhpur", "Bareilly", "Kanpur", "Aligarh", "Muzaffarnagar"] },
  { state: "Gujarat", districts: ["Rajkot", "Junagadh", "Surat", "Vadodara", "Ahmedabad", "Mehsana", "Bhavnagar", "Amreli", "Banaskantha"] },
  { state: "Rajasthan", districts: ["Jaipur", "Kota", "Ganganagar", "Jodhpur", "Alwar", "Bikaner", "Nagaur", "Udaipur", "Hanumangarh"] },
  { state: "Karnataka", districts: ["Belagavi", "Dharwad", "Vijayapura", "Shivamogga", "Mysuru", "Ballari", "Raichur", "Kalaburagi", "Hassan"] },
  { state: "Andhra Pradesh", districts: ["Guntur", "Krishna", "Kurnool", "Anantapur", "West Godavari", "East Godavari", "Chittoor", "Prakasam"] },
  { state: "Telangana", districts: ["Warangal", "Karimnagar", "Nalgonda", "Nizamabad", "Khammam", "Mahabubnagar", "Adilabad"] },
  { state: "Tamil Nadu", districts: ["Thanjavur", "Coimbatore", "Madurai", "Erode", "Tiruchirappalli", "Salem", "Tirunelveli"] },
  { state: "West Bengal", districts: ["Burdwan", "Murshidabad", "Hooghly", "Nadia", "Midnapore", "Birbhum", "Malda"] },
  { state: "Bihar", districts: ["Patna", "Muzaffarpur", "Gaya", "Bhagalpur", "Samastipur", "Purnia", "Rohtas"] },
  { state: "Odisha", districts: ["Bhubaneswar", "Cuttack", "Sambalpur", "Balasore", "Bargarh", "Ganjam"] }
];

// Soil types and characteristics
const SOIL_TYPES = [
  { id: "Black Soil", label: "Black Soil (काळी जमीन / काली मिट्टी)", icon: "🪵", desc: "Clay-rich, high moisture retention, ideal for Cotton, Soybean, Wheat" },
  { id: "Alluvial Soil", label: "Alluvial Soil (गाळाची जमीन / जलोढ़ मिट्टी)", icon: "🌾", desc: "Fertile, loam texture, ideal for Wheat, Paddy, Sugarcane, Maize" },
  { id: "Red Soil", label: "Red Soil (तांबडी जमीन / लाल मिट्टी)", icon: "🧱", desc: "Iron-rich, porous, ideal for Groundnut, Maize, Pulses, Tomato" },
  { id: "Clay Loam", label: "Clay Loam (चिकण दोमट / चिकनी दोमट)", icon: "💧", desc: "Balanced texture, holds water well, ideal for Rice, Wheat, Veggies" },
  { id: "Sandy Soil", label: "Sandy Soil (वाळूमिश्रित / रेतीली मिट्टी)", icon: "🏖️", desc: "Fast drainage, warms quickly, ideal for Bajra, Mustard, Groundnut" },
  { id: "Laterite Soil", label: "Laterite Soil (जांभी जमीन / लैटेराइट)", icon: "🪨", desc: "Leached acidic soil, ideal for Millets, Pulses, Plantation crops" }
];

// Seasons
const SEASONS = [
  { id: "Kharif", label: "🌧 Kharif (Monsoon • June–Oct)", desc: "Sown with arrival of monsoon rains" },
  { id: "Rabi", label: "❄️ Rabi (Winter • Oct–March)", desc: "Sown in autumn and harvested in spring" },
  { id: "Zaid", label: "☀️ Zaid (Summer • March–June)", desc: "Short warm season crop between Rabi & Kharif" }
];
